version: '3.5'
services:

    #APP
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: web-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        env_file:
            - ./docker/app.env
        working_dir: /srv/www
        volumes:
            - ./:/srv/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/nginx/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    #Nginx
    web-server:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: web-server
        restart: unless-stopped
        tty: true
        ports:
            - "81:80"
        volumes:
            - ./:/srv/www
            - ./docker/nginx/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    #Database
    database:
        container_name: my-db
        image: 'mariadb:latest'
        environment:
            - MYSQL_ROOT_PASSWORD=docker
        volumes:
            - ./docker/database/data:/var/lib/mysql
            - ./docker/database/dump:/srv/dump
        ports:
            - "3307:3306"
